### PR TITLE
commiting CollegeTest

### PR DESCRIPTION
**Pull request by KadariKondal**
College Test is commited

### CODE REVIEW

**Comment by BommuKumar** [comment]
hi Kondal,

  add more testcases like group,section..

**Comment by KadariKondal** [comment]
Hi kumar,

      test cases are added . please review and Approve

**Comment by BommuKumar** [comment]
Hi kondal,

   code Approved ,please merge it to master branch

**Comment by KadariKondal** [comment]
Hi Kumar,

  code merged to master branch

**Comment by BommuKumar** [comment]
thanks for merging

**Pull request merged**
